/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.Conexion;
import controlador.ctrlCorte;
import controlador.ctrlProducto;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import modelo.Carrito;
import modelo.Corte;
import modelo.Producto;

/**
 *
 * @author kevin
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    private int idItem;
    ctrlProducto control = new ctrlProducto();
    ArrayList<Carrito> carrito = new ArrayList<>();
    DefaultTableModel modeloCarrito;
    double totalVenta = 0;
    private int idUsuarioSesion;

    public MenuInicio(int idUsuario) {
        initComponents();
        this.setTitle("Punto de venta Jojo");
        control.listarProductos(jtbInventario);
        this.configurarTabla();
        this.idUsuarioSesion = idUsuario;
        this.configurarComboProductos();
        //btnUsuario.setVisible(false);
        //btnEstadisticas.setVisible(false);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/ventay ese s.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jpnInicio = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblVentas = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblProductos = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblInventario = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        lblConsultaR = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        lblReporte = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lblEstad = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        lblMinus = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jpnCuerpo = new javax.swing.JPanel();
        jpnCardInicial = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpnVentas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnEditarCarrito = new javax.swing.JButton();
        btnAgregarCarrito = new javax.swing.JButton();
        sclItems = new javax.swing.JScrollPane();
        jtbCarrito = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtRecib = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        cbbForPago = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        btnFinVenta = new javax.swing.JButton();
        btnEliminarItem = new javax.swing.JButton();
        spnCantidadCarrito = new javax.swing.JSpinner();
        cmbProductos = new javax.swing.JComboBox<>();
        jpnProducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarProd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        txtStockMin = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtpVenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jpnConsulta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        IdItem = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCatConsul = new javax.swing.JTextField();
        txtDesConsul = new javax.swing.JTextField();
        btnConsul = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        scrollInventario1 = new javax.swing.JScrollPane();
        jtbConsulta = new javax.swing.JTable();
        jpnReporte = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();
        lblTotalFinal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblEfectivo = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblTransfer = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblTarjeta = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        spFecha = new javax.swing.JSpinner();
        btnCorte = new javax.swing.JButton();
        jpnUsuario = new javax.swing.JPanel();
        jpnEstadisticas = new javax.swing.JPanel();
        jpnInventario = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        scrollInventario = new javax.swing.JScrollPane();
        jtbInventario = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        jButton4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jButton4.setText("Agregar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jpnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnMenu.setBackground(new java.awt.Color(0, 0, 0));
        jpnMenu.setForeground(new java.awt.Color(255, 255, 255));
        jpnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jpnMenu.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Ventas");
        jpnMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lblVentas.setBackground(new java.awt.Color(153, 153, 255));
        lblVentas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
        });
        lblVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ventas");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        lblVentas.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, -1));

        jpnMenu.add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, 60));

        lblProductos.setBackground(new java.awt.Color(153, 153, 255));
        lblProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosMouseClicked(evt);
            }
        });
        lblProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Productos");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        lblProductos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, -1));

        jpnMenu.add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 60));

        lblInventario.setBackground(new java.awt.Color(153, 153, 255));
        lblInventario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInventarioMouseClicked(evt);
            }
        });
        lblInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Inventario");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        lblInventario.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, -1));

        jpnMenu.add(lblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 60));

        lblConsultaR.setBackground(new java.awt.Color(153, 153, 255));
        lblConsultaR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblConsultaR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultaRMouseClicked(evt);
            }
        });
        lblConsultaR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Consulta rápida");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        lblConsultaR.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 120, -1));

        jpnMenu.add(lblConsultaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, 60));

        lblReporte.setBackground(new java.awt.Color(153, 153, 255));
        lblReporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReporteMouseClicked(evt);
            }
        });
        lblReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Reporte");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        lblReporte.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, -1));

        jpnMenu.add(lblReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 280, 60));

        lblUsuario.setBackground(new java.awt.Color(153, 153, 255));
        lblUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseClicked(evt);
            }
        });
        lblUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Usuario");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        lblUsuario.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, -1));

        jpnMenu.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 280, 60));

        lblEstad.setBackground(new java.awt.Color(153, 153, 255));
        lblEstad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblEstad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEstadMouseClicked(evt);
            }
        });
        lblEstad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Estadísticas");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        lblEstad.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, -1));

        jpnMenu.add(lblEstad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 280, 60));

        lblMinus.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        lblMinus.setForeground(new java.awt.Color(255, 255, 255));
        lblMinus.setText("—");
        jpnMenu.add(lblMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        lblExit.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jpnMenu.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jpnInicio.add(jpnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 600));

        jpnCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        jpnCuerpo.setMaximumSize(new java.awt.Dimension(1200, 700));
        jpnCuerpo.setLayout(new java.awt.CardLayout());

        jpnCardInicial.setBackground(new java.awt.Color(0, 0, 0));
        jpnCardInicial.setPreferredSize(new java.awt.Dimension(866, 469));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido");

        javax.swing.GroupLayout jpnCardInicialLayout = new javax.swing.GroupLayout(jpnCardInicial);
        jpnCardInicial.setLayout(jpnCardInicialLayout);
        jpnCardInicialLayout.setHorizontalGroup(
            jpnCardInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCardInicialLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel3)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jpnCardInicialLayout.setVerticalGroup(
            jpnCardInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCardInicialLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel3)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        jpnCuerpo.add(jpnCardInicial, "Inicio");

        jpnVentas.setBackground(new java.awt.Color(0, 0, 0));
        jpnVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Registrar venta");
        jpnVentas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 24, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Descripcion");
        jpnVentas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 74, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cantidad");
        jpnVentas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 73, -1, 22));

        btnEditarCarrito.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        btnEditarCarrito.setText("Editar");
        btnEditarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCarritoActionPerformed(evt);
            }
        });
        jpnVentas.add(btnEditarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        btnAgregarCarrito.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        btnAgregarCarrito.setText("Agregar");
        btnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarritoActionPerformed(evt);
            }
        });
        jpnVentas.add(btnAgregarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        jtbCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sclItems.setViewportView(jtbCarrito);

        jpnVentas.add(sclItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 610, 390));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total         $");

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Recibido  $");

        lblTotal.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("0.00");

        txtRecib.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        txtRecib.setText("0.00");
        txtRecib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecibActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cambio   $");

        lblCambio.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        lblCambio.setForeground(new java.awt.Color(255, 255, 255));
        lblCambio.setText("0.00");

        btnCalcular.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        btnCalcular.setText("Cambio");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        cbbForPago.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        cbbForPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Transferencia", "Tarjeta" }));

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Forma de pago");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRecib, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(cbbForPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtRecib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblCambio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(cbbForPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpnVentas.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 217, -1, -1));

        btnFinVenta.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        btnFinVenta.setText("Finalizar");
        btnFinVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinVentaActionPerformed(evt);
            }
        });
        jpnVentas.add(btnFinVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, -1));

        btnEliminarItem.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        btnEliminarItem.setText("Eliminar");
        btnEliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarItemActionPerformed(evt);
            }
        });
        jpnVentas.add(btnEliminarItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));
        jpnVentas.add(spnCantidadCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        cmbProductos.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jpnVentas.add(cmbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, -1));

        jpnCuerpo.add(jpnVentas, "Ventas");

        jpnProducto.setBackground(new java.awt.Color(0, 0, 0));
        jpnProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripción:");
        jpnProducto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 129, -1, -1));

        btnGuardarProd.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnGuardarProd.setText("Guardar");
        btnGuardarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProdActionPerformed(evt);
            }
        });
        jpnProducto.add(btnGuardarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto");
        jpnProducto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 64, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stock:");
        jpnProducto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock Min:");
        jpnProducto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Costo:");
        jpnProducto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio de venta:");
        jpnProducto.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Categoría:");
        jpnProducto.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        txtCosto.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        jpnProducto.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 410, -1));

        txtStockMin.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtStockMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockMinActionPerformed(evt);
            }
        });
        jpnProducto.add(txtStockMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 410, -1));

        txtStock.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        jpnProducto.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 410, -1));

        txtCategoria.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        jpnProducto.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 410, -1));

        txtpVenta.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtpVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpVentaActionPerformed(evt);
            }
        });
        jpnProducto.add(txtpVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 410, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jpnProducto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 129, 460, -1));

        jpnCuerpo.add(jpnProducto, "Productos");

        jpnConsulta.setBackground(new java.awt.Color(0, 0, 0));
        jpnConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Consulta rápida");
        jpnConsulta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        IdItem.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        IdItem.setForeground(new java.awt.Color(255, 255, 255));
        IdItem.setText("Categoria");
        jpnConsulta.add(IdItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 103, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descripción");
        jpnConsulta.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 144, -1, -1));

        txtCatConsul.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jpnConsulta.add(txtCatConsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 103, 122, -1));

        txtDesConsul.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jpnConsulta.add(txtDesConsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 144, 122, -1));

        btnConsul.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnConsul.setText("Buscar");
        btnConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulActionPerformed(evt);
            }
        });
        jpnConsulta.add(btnConsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollInventario1.setViewportView(jtbConsulta);

        jPanel3.add(scrollInventario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 240));

        jpnConsulta.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 710, 260));

        jpnCuerpo.add(jpnConsulta, "Consulta");

        jpnReporte.setBackground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total:");

        btnPDF.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnPDF.setText("PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        lblTotalFinal.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblTotalFinal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalFinal.setText("0.00");

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Reporte de ventas | Corte de caja");

        lblEfectivo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        lblEfectivo.setText("0.00");

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Efectivo:");

        lblTransfer.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblTransfer.setForeground(new java.awt.Color(255, 255, 255));
        lblTransfer.setText("0.00");

        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Transferencia:");

        lblTarjeta.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        lblTarjeta.setText("0.00");

        jLabel28.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Tarjeta:");

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Seleccione la fecha");

        spFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1767850427028L), null, null, java.util.Calendar.DAY_OF_MONTH));

        btnCorte.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnCorte.setText("Corte");
        btnCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnReporteLayout = new javax.swing.GroupLayout(jpnReporte);
        jpnReporte.setLayout(jpnReporteLayout);
        jpnReporteLayout.setHorizontalGroup(
            jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnReporteLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnReporteLayout.createSequentialGroup()
                        .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnReporteLayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(lblTarjeta))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jpnReporteLayout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTransfer))
                                        .addGroup(jpnReporteLayout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addGap(91, 91, 91)
                                            .addComponent(lblEfectivo))))
                                .addGroup(jpnReporteLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalFinal))))
                        .addContainerGap(641, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnReporteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCorte)
                            .addComponent(btnPDF))
                        .addGap(60, 60, 60))))
            .addGroup(jpnReporteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(spFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnReporteLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel18)
                    .addContainerGap(574, Short.MAX_VALUE)))
        );
        jpnReporteLayout.setVerticalGroup(
            jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnReporteLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(btnCorte))
                .addGap(18, 18, 18)
                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblTotalFinal))
                .addGap(28, 28, 28)
                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfectivo)
                    .addComponent(jLabel24))
                .addGap(42, 42, 42)
                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransfer)
                    .addComponent(jLabel26))
                .addGap(27, 27, 27)
                .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTarjeta)
                    .addComponent(jLabel28))
                .addGap(124, 124, 124))
            .addGroup(jpnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnReporteLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel18)
                    .addContainerGap(544, Short.MAX_VALUE)))
        );

        jpnCuerpo.add(jpnReporte, "Reporte");

        javax.swing.GroupLayout jpnUsuarioLayout = new javax.swing.GroupLayout(jpnUsuario);
        jpnUsuario.setLayout(jpnUsuarioLayout);
        jpnUsuarioLayout.setHorizontalGroup(
            jpnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );
        jpnUsuarioLayout.setVerticalGroup(
            jpnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jpnCuerpo.add(jpnUsuario, "Usuario");

        javax.swing.GroupLayout jpnEstadisticasLayout = new javax.swing.GroupLayout(jpnEstadisticas);
        jpnEstadisticas.setLayout(jpnEstadisticasLayout);
        jpnEstadisticasLayout.setHorizontalGroup(
            jpnEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );
        jpnEstadisticasLayout.setVerticalGroup(
            jpnEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jpnCuerpo.add(jpnEstadisticas, "Estadisticas");

        jpnInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollInventario.setViewportView(jtbInventario);

        jPanel2.add(scrollInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 440));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 710, 460));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inventario");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnBorrar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        btnBuscarProd.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        btnEditar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, -1, -1));

        btnMostrar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, -1, -1));

        jpnInventario.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        jpnCuerpo.add(jpnInventario, "Inventario");

        jpnInicio.add(jpnCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCarritoActionPerformed
        // TODO add your handling code here:
        int fila = jtbCarrito.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un item");
            return;
        }

        int nuevaCantidad = Integer.parseInt(
                JOptionPane.showInputDialog("Nueva cantidad")
        );

        double precio = (double) modeloCarrito.getValueAt(fila, 2);
        double nuevoSubtotal = nuevaCantidad * precio;

        modeloCarrito.setValueAt(nuevaCantidad, fila, 3);
        modeloCarrito.setValueAt(nuevoSubtotal, fila, 4);

        recalcularTotal();
    }//GEN-LAST:event_btnEditarCarritoActionPerformed

    private void txtRecibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecibActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            double recibido = Double.parseDouble(txtRecib.getText().trim());

            if (recibido < totalVenta) {
                JOptionPane.showMessageDialog(this, "Monto insuficiente");
                return;
            }

            double cambio = recibido - totalVenta;
            lblCambio.setText(String.valueOf(cambio));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto válido");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnFinVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinVentaActionPerformed
        // TODO add your handling code here:
        if (modeloCarrito.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Carrito vacío");
            return;
        }
        boolean ok = guardarVenta();

        if (ok) {
            JOptionPane.showMessageDialog(this, "Venta realizada");
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar venta");
        }

    }//GEN-LAST:event_btnFinVentaActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtStockMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMinActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void txtpVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpVentaActionPerformed

    private void btnGuardarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProdActionPerformed
        // TODO add your handling code here:
        Producto producto = new Producto();
        ctrlProducto controlProd = new ctrlProducto();
        //validar campos
        if (txtDescripcion.getText().isEmpty() || txtStock.getText().isEmpty() || txtStockMin.getText().isEmpty() || txtCategoria.getText().isEmpty() || txtpVenta.getText().isEmpty() || txtCosto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else if (!controlProd.existeProducto(txtDescripcion.getText().trim())) {
            try {
                producto.setDescripcion(txtDescripcion.getText().trim());
                producto.setStock(Integer.parseInt(txtStock.getText().trim()));
                producto.setStockMin(Integer.parseInt(txtStockMin.getText().trim()));
                producto.setCosto(Double.parseDouble(txtCosto.getText().trim()));
                producto.setpVenta(Double.parseDouble(txtpVenta.getText().trim()));
                producto.setCategoria(txtCategoria.getText().trim());
                producto.setEstado(true);

                if (controlProd.guardar(producto)) {
                    JOptionPane.showMessageDialog(null, "Registro guardado");
                    this.limpiarProducto();
                    control.listarProductos(jtbInventario);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar el producto ");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al guardar el producto ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El registro ya existe en la base de datos");
        }

    }//GEN-LAST:event_btnGuardarProdActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila = jtbInventario.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }

        Producto p = new Producto();

        String descripcion = JOptionPane.showInputDialog(
                this,
                "Ingrese la nueva descripción:",
                jtbInventario.getValueAt(fila, 1)
        );

        int stock = Integer.parseInt(JOptionPane.showInputDialog(
                this,
                "Ingrese el nuevo stock:",
                jtbInventario.getValueAt(fila, 2)
        ));

        int stockMin = Integer.parseInt(JOptionPane.showInputDialog(
                this,
                "Ingrese el nuevo stock mínimo:",
                jtbInventario.getValueAt(fila, 3)
        ));

        double costo = Double.parseDouble(JOptionPane.showInputDialog(
                this,
                "Ingrese el nuevo costo:",
                jtbInventario.getValueAt(fila, 4)
        ));

        double pventa = Double.parseDouble(JOptionPane.showInputDialog(
                this,
                "Ingrese el nuevo precio:",
                jtbInventario.getValueAt(fila, 5)
        ));

        String categoria = JOptionPane.showInputDialog(
                this,
                "Ingrese la nueva categoría:",
                jtbInventario.getValueAt(fila, 6)
        );

        p.setIdItem(Integer.parseInt(jtbInventario.getValueAt(fila, 0).toString()));
        p.setDescripcion(descripcion);
        p.setStock(stock);
        p.setStockMin(stockMin);
        p.setCosto(costo);
        p.setpVenta(pventa);
        p.setCategoria(categoria);
        p.setEstado(true);

        if (control.editarProducto(p)) {
            JOptionPane.showMessageDialog(this, "Producto actualizado");
            control.listarProductos(jtbInventario);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int fila = jtbInventario.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar este producto?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        int idProducto = Integer.parseInt(
                jtbInventario.getValueAt(fila, 0).toString()
        );

        if (control.eliminarProducto(idProducto)) {
            JOptionPane.showMessageDialog(this, "Eliminado correctamente");
            control.listarProductos(jtbInventario);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        // TODO add your handling code here:
        String texto = JOptionPane.showInputDialog(
                this,
                "Buscar por categoría o descripción:"
        ).trim();

        if (texto.isEmpty()) {
            control.listarProductos(jtbInventario);
        } else {
            control.buscarProductos(jtbInventario, texto);
        }

    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        control.listarProductos(jtbInventario);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulActionPerformed
        // TODO add your handling code here:
        String descripcion = txtDesConsul.getText().trim();
        String categoria = txtCatConsul.getText().trim();

        if (descripcion.isEmpty() && categoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese descripción o categoría");
            return;
        }

        // Prioriza descripción si existe, si no usa categoría
        String textoBusqueda = !descripcion.isEmpty() ? descripcion : categoria;

        // MISMA forma que el buscar normal
        control.buscarProductos(jtbConsulta, textoBusqueda);

        // opcional: limpiar inputs
        txtDesConsul.setText("");
        txtCatConsul.setText("");
    }//GEN-LAST:event_btnConsulActionPerformed

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
        // TODO add your handling code here:
        if (cmbProductos.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }

        String descripcion = cmbProductos.getSelectedItem().toString();
        int cantidad = (int) spnCantidadCarrito.getValue();

        ctrlProducto cp = new ctrlProducto();
        Producto p = cp.buscarPorDescripcion(descripcion);

        if (p == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
            return;
        }

        if (cantidad > p.getStock()) {
            JOptionPane.showMessageDialog(this, "Stock insuficiente");
            return;
        }

        double subtotal = cantidad * p.getpVenta();

        modeloCarrito.addRow(new Object[]{
            p.getIdItem(),
            p.getDescripcion(),
            p.getpVenta(),
            cantidad,
            subtotal
        });

        recalcularTotal();
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnEliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarItemActionPerformed
        // TODO add your handling code here:
        int fila = jtbCarrito.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un item");
            return;
        }

        modeloCarrito.removeRow(fila);
        recalcularTotal();
    }//GEN-LAST:event_btnEliminarItemActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
        java.util.Date fechaSpinner = (java.util.Date) spFecha.getValue();

        ctrlCorte ctrl = new ctrlCorte();
        ctrl.generarCorteCaja(fechaSpinner);

    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteActionPerformed
        // TODO add your handling code here:
        java.util.Date fechaSpinner = (java.util.Date) spFecha.getValue();

        ctrlCorte ctrl = new ctrlCorte();
        Corte totales = ctrl.obtenerTotales(fechaSpinner);

        lblEfectivo.setText(String.valueOf(totales.getEfectivo()));
        lblTarjeta.setText(String.valueOf(totales.getTarjeta()));
        lblTransfer.setText(String.valueOf(totales.getTransferencia()));
        lblTotalFinal.setText(String.valueOf(totales.getTotalGeneral()));

    }//GEN-LAST:event_btnCorteActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked

    }//GEN-LAST:event_jLabel19MouseClicked

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpnCuerpo.getLayout();
        card.show(jpnCuerpo, "Ventas");
        this.configurarComboProductos();
    }//GEN-LAST:event_lblVentasMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void lblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpnCuerpo.getLayout();
        card.show(jpnCuerpo, "Productos");
    }//GEN-LAST:event_lblProductosMouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void lblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpnCuerpo.getLayout();
        card.show(jpnCuerpo, "Inventario");
    }//GEN-LAST:event_lblInventarioMouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void lblConsultaRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaRMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpnCuerpo.getLayout();
        card.show(jpnCuerpo, "Consulta");
    }//GEN-LAST:event_lblConsultaRMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void lblReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpnCuerpo.getLayout();
        card.show(jpnCuerpo, "Reporte");
        this.configurarSpinnerFecha();
    }//GEN-LAST:event_lblReporteMouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel31MouseClicked

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpnCuerpo.getLayout();
        card.show(jpnCuerpo, "Usuario");
    }//GEN-LAST:event_lblUsuarioMouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel32MouseClicked

    private void lblEstadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstadMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpnCuerpo.getLayout();
        card.show(jpnCuerpo, "Estadisticas");
    }//GEN-LAST:event_lblEstadMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        this.setBackground(Color.red);
        this.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        this.setBackground(Color.black);
        this.setForeground(Color.white);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(this, "¿En verdad desea salir?");
        if(op==0){
            System.exit(0);
        } else {
            //nada
        }
    }//GEN-LAST:event_lblExitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdItem;
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnConsul;
    private javax.swing.JButton btnCorte;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarCarrito;
    private javax.swing.JButton btnEliminarItem;
    private javax.swing.JButton btnFinVenta;
    private javax.swing.JButton btnGuardarProd;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JComboBox<String> cbbForPago;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnCardInicial;
    private javax.swing.JPanel jpnConsulta;
    private javax.swing.JPanel jpnCuerpo;
    private javax.swing.JPanel jpnEstadisticas;
    private javax.swing.JPanel jpnInicio;
    private javax.swing.JPanel jpnInventario;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnProducto;
    private javax.swing.JPanel jpnReporte;
    private javax.swing.JPanel jpnUsuario;
    private javax.swing.JPanel jpnVentas;
    public static javax.swing.JTable jtbCarrito;
    public static javax.swing.JTable jtbConsulta;
    public static javax.swing.JTable jtbInventario;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JPanel lblConsultaR;
    private javax.swing.JLabel lblEfectivo;
    private javax.swing.JPanel lblEstad;
    private javax.swing.JLabel lblExit;
    private javax.swing.JPanel lblInventario;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinus;
    private javax.swing.JPanel lblProductos;
    private javax.swing.JPanel lblReporte;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalFinal;
    private javax.swing.JLabel lblTransfer;
    private javax.swing.JPanel lblUsuario;
    private javax.swing.JPanel lblVentas;
    private javax.swing.JScrollPane sclItems;
    public static javax.swing.JScrollPane scrollInventario;
    public static javax.swing.JScrollPane scrollInventario1;
    private javax.swing.JSpinner spFecha;
    private javax.swing.JSpinner spnCantidadCarrito;
    private javax.swing.JTextField txtCatConsul;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDesConsul;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtRecib;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStockMin;
    private javax.swing.JTextField txtpVenta;
    // End of variables declaration//GEN-END:variables

//metodos adicionales
    public void limpiarProducto() {
        txtDescripcion.setText("");
        txtStock.setText("");
        txtStockMin.setText("");
        txtCosto.setText("");
        txtpVenta.setText("");
        txtCategoria.setText("");
    }

    private void refrescarTabla() {
        modeloCarrito.setRowCount(0);
        totalVenta = 0;

        for (Carrito i : carrito) {
            modeloCarrito.addRow(new Object[]{
                i.getIdProducto(),
                i.getDescripcion(),
                i.getPrecio(),
                i.getCantidad(),
                i.getSubtotal()
            });
            totalVenta += i.getSubtotal();
        }

        lblTotal.setText("$" + String.format("%.2f", totalVenta));
    }

    private void configurarTabla() {
        modeloCarrito = new DefaultTableModel(
                new Object[]{"ID", "Descripción", "Precio", "Cantidad", "Subtotal"}, 0
        );
        jtbCarrito.setModel(modeloCarrito);
    }

    private void recalcularTotal() {
        totalVenta = 0.0;

        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            totalVenta += (double) modeloCarrito.getValueAt(i, 4);
        }

        lblTotal.setText(String.valueOf(totalVenta));
    }

    private boolean guardarVenta() {

        Connection cn = Conexion.conectar();

        try {
            cn.setAutoCommit(false); // ← transacción

            // 1. Guardar cabecera
            String sqlCab = "INSERT INTO tb_ventasCabecera(total, formaPago, hora, estado, idUsuario) VALUES( ?,  ?, NOW(), 1,  ?)";

            PreparedStatement psCab = cn.prepareStatement(
                    sqlCab, Statement.RETURN_GENERATED_KEYS
            );

            psCab.setDouble(1, totalVenta);
            psCab.setString(2, cbbForPago.getSelectedItem().toString());
            psCab.setInt(3, idUsuarioSesion);

            psCab.executeUpdate();

            ResultSet rs = psCab.getGeneratedKeys();
            if (!rs.next()) {
                cn.rollback();
                return false;
            }

            int idCabecera = rs.getInt(1);

            // 2. Guardar detalle y descontar stock
            String sqlDet = "INSERT INTO tb_ventasDetalle(idCabeceraVenta, idProducto, precioU, cantidad) VALUES( ?,  ?,  ?,  ?)";

            PreparedStatement psDet = cn.prepareStatement(sqlDet);

            String sqlStock = "UPDATE tb_Inventario SET stock = stock - ? WHERE  idItem = ? ";

            PreparedStatement psStock = cn.prepareStatement(sqlStock);

            for (int i = 0; i < modeloCarrito.getRowCount(); i++) {

                int idProd = (int) modeloCarrito.getValueAt(i, 0);
                double precio = (double) modeloCarrito.getValueAt(i, 2);
                int cantidad = (int) modeloCarrito.getValueAt(i, 3);

                psDet.setInt(1, idCabecera);
                psDet.setInt(2, idProd);
                psDet.setDouble(3, precio);
                psDet.setInt(4, cantidad);
                psDet.executeUpdate();

                psStock.setInt(1, cantidad);
                psStock.setInt(2, idProd);
                psStock.executeUpdate();
            }

            cn.commit();
            return true;

        } catch (SQLException e) {
            try {
                cn.rollback();
            } catch (SQLException ex) {
            }
            System.out.println("Error guardar venta " + e);
            return false;

        } finally {
            try {
                cn.setAutoCommit(true);
                cn.close();
            } catch (SQLException e) {
            }
        }
    }

    private void configurarComboProductos() {

        cmbProductos.removeAllItems();

        String sql = "SELECT descripcion FROM tb_Inventario WHERE estado = 1";

        try (Connection cn = Conexion.conectar();
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                cmbProductos.addItem(rs.getString("descripcion"));
            }

        } catch (SQLException e) {
            System.out.println("Error cargar productos " + e);
        }
    }

    private void configurarSpinnerFecha() {
        SpinnerDateModel modeloFecha = new SpinnerDateModel();
        spFecha.setModel(modeloFecha);

        JSpinner.DateEditor editor
                = new JSpinner.DateEditor(spFecha, "yyyy-MM-dd");
        spFecha.setEditor(editor);
    }

}
